### ISSUE TITLE
Compile time errors

### ISSUE THREAD

**Issue by SAPIENTechnologies** [AndreaMiotto/ActionOver#1]
Hello. I have installed this package as directed and have tried to follow your code example. Rather than put it directly into contentView, I have created an ActionButton with body as such...

`    var body: some View {
        Button(
            action: { self.showActions = true},
            label: { Image(systemName: "plus").font(.title) }
        )
        .actionOver(
                presented: $showActions,
                title: "Options",
                message: "",
                buttons: buttons,
                ipadAndMacConfiguration: ipadMacConfig
        )
}`

I create ActionButton array as your sample shows and an ipadMacConfig.

The following errors appear:
Use of undeclared type 'ActionOverButton'
Use of unresolved identifier 'IpadAndMacConfiguration'
'actionOver' is inaccessible due to 'internal' protection level

I have tried importing ActionOver to no avail. Any ideas?

**Comment by AndreaMiotto** [comment]
fixed with the public init, sorry, my fault
