### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by SAPIENTechnologies** [AndreaMiotto/ActionOver#2]
I have a couple of minor changes I would like to suggest that I have implemented on a branch. I can list them here or create a PR. Which do you prefer? I guess I need better access to create a PR?

**Comment by AndreaMiotto** [comment]
Hi there, you can create a PR, you don't need any special permissions

**Comment by SAPIENTechnologies** [comment]
I get the message "It looks like you don't have write access to andreamiotto/ActionOver. if you should, please check with repository administrator.

Then it asks if I want to fork it into my personal repo. Sorry. i have not done many pull requests.

**Comment by AndreaMiotto** [comment]
Yes, that right, you have to fork it, and once you have done, you can create a new pull request
