### ISSUE TITLE
Extra { on line 160

### ISSUE THREAD

**Issue by SAPIENTechnologies** [AndreaMiotto/ActionOver#5]
You seemed to have picked up an extra curly bracket on line 160 of ActionOverViewModifier.swift which causes a failure at compile time.

**Comment by AndreaMiotto** [comment]
Fixed, I will try to implement a Github action to prevent this to happen again.
Try version 1.0.4

**Comment by SAPIENTechnologies** [comment]
Still only giving me 1.0.3


On Apr 28, 2020, at 3:01 PM, Andrea Miotto <notifications@github.com <mailto:notifications@github.com> > wrote:


Fixed, I will try to implement a Github action to prevent this to happen again.
Try version 1.0.4

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

<http://schema.org>

**Comment by AndreaMiotto** [comment]
I've updated version 1.0.3, I didn't like to leave a version with compiling errors.Just re-download the version 1.0.3

**Comment by SAPIENTechnologies** [comment]
As an aside, where does one set the version info that is used in Xcode when connecting to a swift package? I assume it is somewhere in their code, but i don’t see anywhere in their Package.swift where this gets set.

I am asking for another dev who does not know where to set this…



Thanks in advance…


On Apr 28, 2020, at 3:05 PM, Andrea Miotto <notifications@github.com <mailto:notifications@github.com> > wrote:


I've updated version 1.0.3, I didn't like to leave a version with compiling errors.Just re-download the version 1.0.3
