### ISSUE TITLE
Runtime error on macOS - needs 10.15.4

### ISSUE THREAD

**Issue by WholeCheese** [AndreaMiotto/ActionOver#6]
Andrea, thank you for this code!  However, I am attempting to run it via Catalyst on my Mac and I am getting this error:

`application requires at least OS X version 10.15.4 (10.15.4), but is being run on 10.15.3 ( 10.15.3/19D76), and so is exiting.`

I am using Xcode 11.4.1 and have been able to run other Catalyst apps under 10.15.3 so what is the problem here?  I've searched the code looking for special OS requirements but can't find any.

Now, before you suggest I update to 10.15.4 let me tell you my horror story.  I did update to 10.15.4 and I have spent the last five days trying undo that foolish decision!  10.15.4 is a nightmare of bugs.  Mail, Messages, Contacts, Spotlight, all break with the "not responding" status.  I had an external boot disk with 10.15.3 but some obtuse security "feature" in 10.15.4 prevents using an external disk as a startup disk.  After days of searching for a backdate solution I was finally able to restore my machine back to 10.15.3.

Any ideas?

**Comment by AndreaMiotto** [comment]
Hi Allan.
With 10.15.4 Apple has released a very important fix for popup view.
That's why I've set this minimum requirement, I will update the readme.

**Comment by WholeCheese** [comment]
Ok, but are you actually running macOS 10.15.4?!?  What model of Mac are you using?  Have you experienced any problems in .4?  I have a new (as of January) MBP and when I upgraded to .4 too many important Apple apps broke.  A clean install of .4 did not fix it.  Also, I cannot find anywhere in Xcode where you can set .4 as a requirement.  I only see the major and minor 10.15, 10.14... deployment target setting.

In the meantime, it looks like I will have to wait until 10.15.5! :-)

Oh, and BTW, thank you for responding so quickly!!  You are a gem!

-Allan

**Comment by AndreaMiotto** [comment]
Yes, I'm using 10.15.14 and I'm not having many issues.
The .4 is set in the example project, so you could actually be able to run the package in one of your projects.

<img width="1049" alt="Screen Shot 2020-04-29 at 5 43 41 pm" src="https://user-images.githubusercontent.com/11211914/80572119-0fc07580-8a41-11ea-9532-c9d9b6699f75.png">

**Comment by WholeCheese** [comment]
Yes, I saw the target check mark for Mac, this is how you turn on Catalyst. I have this in a few of my other projects which run in 10.15.3.  But the requirement here only says “requires macOS 10.15”.  Where is the requirement for 10.15.4?  If you are using a particular SwiftUI feature that requires 10.15.4 or newer then that code should be wrapped in a conditional.

**Comment by WholeCheese** [comment]
Andrea,

Again, the Xcode project target settings do not specify 10.15.4, it only presents 10.15, hence that is why it compiles successfully under 10.15.3

Could you please identify the place in your code that explicitly requires 10.15.4?

Is there a workaround?  If so, the code should be wrapped in a "if #available(macOS 10.15.4, *)"
